# Generated by Django 2.2.10 on 2021-11-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaires",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("end", models.DateTimeField()),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("type", models.IntegerField()),
                ("text", models.CharField(max_length=100)),
                (
                    "Questionnaire_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Questionnaires",
                    ),
                ),
            ],
        ),
    ]
